language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
env:
  - FORCE_COLOR: 1
branches:
  only:
    - master
    - /^greenkeeper.*$/

before_script:
  - ./scripts/run-on-node-version.sh 10 "greenkeeper-lockfile-update"

script:
  - npm run verify

after_success:
  - npm install -g travis-deploy-once@4
  - travis-deploy-once "npx semantic-release"
  - ./scripts/run-on-node-version.sh 10 "npx codecov"

after_script:
  - ./scripts/run-on-node-version.sh 10 "greenkeeper-lockfile-upload"
